### PR TITLE
New license and splash

### PR DESCRIPTION
**Pull request by ccarouge**
This branch:

- removes the Apache License
- adds a CC0 waiver in the README.md for the GitHub repo
- adds a new Home page for the Community site with the CC0 waiver
- adds a new Home page for the ACCESS-NRI Hub with a CC-BY 4.0 license

### CODE REVIEW

**Review by rbeucher — APPROVED** [review]
Good I think you can merge this.

**Comment by aidanheerdegen** [comment]
I think it is time to get rid of the work in progress. I think it is confusing for users, it undermines trust in the content IMO.

**Comment by rbeucher** [comment]
Actually, I agree with @aidanheerdegen on this.

**Review by rbeucher — APPROVED** [review]

**Comment by ccarouge** [comment]
There were a few instances of the old names and I've also changed the names of the sites accordingly, so less hyphens.

**Pull request merged**
