### PR TITLE
Add Google Analytics

### LINKED ISSUE #66: Setup site analytics for Hub
https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/

### PR DESCRIPTION
**Pull request by rbeucher**
This will add Google Analytics to the Hub

close #66

### CODE REVIEW

**Comment by ccarouge** [comment]
I thought we were going to look at plausible other options?

**Comment by rbeucher** [comment]
I think only GA is supported by mkdocs...
We can always remove it but I thought it would be good to have some stats during the review process...

**Comment by ccarouge** [comment]
That's fine, I just wanted to understand the link between our Slack conversation and the PR.

**Comment by rbeucher** [comment]
If you want advanced analytics and if we have lots of visitor we will have to pay for GA. 
I don't think this will happen though and we can do with the free plan

**Review by ccarouge — APPROVED** [review]

**Pull request merged**
